### ISSUE TITLE
Plugin is throwing errors reporting that Key expiry has failed!

### ISSUE THREAD

**Issue by jdesulme** [Libertymutual/ssh-key-enforcer-stash#22]
We're running Bitbucket 4.13.1 and we're seeing the following error in our logs. I wonder if there an endpoint available that shows a historical overview of keys that have been rotated. 

```2017-03-20 15:36:29,293 ERROR [Caesium-1-4]  c.l.f.s.s.s.KeyRotationJobRunner Key expiry failed!
2017-03-20 15:36:29,293 ERROR [Caesium-1-4]  c.l.f.s.s.s.KeyRotationJobRunner Key expiry failed!
java.lang.IllegalStateException: plugin [{com.lmig.forge.stash.ssh.stash-ssh-key-enforcer}] invoking ActiveObjects before <ao> configuration module is enabled or plugin is missing an <ao> configuration module. Note that scanning of entities from the ao.model package is no longer supported.
        at com.atlassian.activeobjects.osgi.TenantAwareActiveObjects.delegate(TenantAwareActiveObjects.java:165) ~[na:na]
        at com.atlassian.activeobjects.osgi.TenantAwareActiveObjects.find(TenantAwareActiveObjects.java:296) ~[na:na]
        at org.eclipse.gemini.blueprint.service.importer.support.internal.aop.ServiceInvoker.doInvoke(ServiceInvoker.java:56) ~[na:na]
        at org.eclipse.gemini.blueprint.service.importer.support.internal.aop.ServiceInvoker.invoke(ServiceInvoker.java:60) ~[na:na]
        at org.eclipse.gemini.blueprint.service.util.internal.aop.ServiceTCCLInterceptor.invokeUnprivileged(ServiceTCCLInterceptor.java:70) ~[na:na]
        at org.eclipse.gemini.blueprint.service.util.internal.aop.ServiceTCCLInterceptor.invoke(ServiceTCCLInterceptor.java:53) ~[na:na]
        at org.eclipse.gemini.blueprint.service.importer.support.LocalBundleContextAdvice.invoke(LocalBundleContextAdvice.java:57) ~[na:na]
        at com.lmig.forge.stash.ssh.ao.EnterpriseKeyRepositoryImpl.listOfExpiredKeys(EnterpriseKeyRepositoryImpl.java:95) ~[plugin_2434508853149467232_stash-ssh-key-enforcer-2.0.0_1489690730000.jar:na]
        at com.lmig.forge.stash.ssh.keys.EnterpriseSshKeyServiceImpl.replaceExpiredKeysAndNotifyUsers(EnterpriseSshKeyServiceImpl.java:122) ~[plugin_2434508853149467232_stash-ssh-key-enforcer-2.0.0_1489690730000.jar:na]
        at com.lmig.forge.stash.ssh.scheduler.KeyRotationOperation.perform(KeyRotationOperation.java:30) ~[plugin_2434508853149467232_stash-ssh-key-enforcer-2.0.0_1489690730000.jar:na]
        at com.lmig.forge.stash.ssh.scheduler.KeyRotationOperation.perform(KeyRotationOperation.java:21) ~[plugin_2434508853149467232_stash-ssh-key-enforcer-2.0.0_1489690730000.jar:na]
        at com.atlassian.stash.internal.user.DefaultEscalatedSecurityContext.call(DefaultEscalatedSecurityContext.java:51) ~[bitbucket-service-impl-4.13.1.jar:na]
        at com.lmig.forge.stash.ssh.scheduler.KeyRotationJobRunner.runJob(KeyRotationJobRunner.java:54) ~[plugin_2434508853149467232_stash-ssh-key-enforcer-2.0.0_1489690730000.jar:na]
        at com.atlassian.scheduler.core.JobLauncher.runJob(JobLauncher.java:153) [atlassian-scheduler-core-1.7.0.jar:na]
        at com.atlassian.scheduler.core.JobLauncher.launchAndBuildResponse(JobLauncher.java:118) [atlassian-scheduler-core-1.7.0.jar:na]
        at com.atlassian.scheduler.core.JobLauncher.launch(JobLauncher.java:97) [atlassian-scheduler-core-1.7.0.jar:na]
        at com.atlassian.scheduler.caesium.impl.CaesiumSchedulerService.launchJob(CaesiumSchedulerService.java:401) [atlassian-scheduler-caesium-1.3.0.jar:na]
        at com.atlassian.scheduler.caesium.impl.CaesiumSchedulerService.executeClusteredJob(CaesiumSchedulerService.java:396) [atlassian-scheduler-caesium-1.3.0.jar:na]
        at com.atlassian.scheduler.caesium.impl.CaesiumSchedulerService.executeQueuedJob(CaesiumSchedulerService.java:349) [atlassian-scheduler-caesium-1.3.0.jar:na]
        at com.atlassian.scheduler.caesium.impl.CaesiumSchedulerService$1.consume(CaesiumSchedulerService.java:255) [atlassian-scheduler-caesium-1.3.0.jar:na]
        at com.atlassian.scheduler.caesium.impl.CaesiumSchedulerService$1.consume(CaesiumSchedulerService.java:252) [atlassian-scheduler-caesium-1.3.0.jar:na]
        at com.atlassian.scheduler.caesium.impl.SchedulerQueueWorker.executeJob(SchedulerQueueWorker.java:65) [atlassian-scheduler-caesium-1.3.0.jar:na]
        at com.atlassian.scheduler.caesium.impl.SchedulerQueueWorker.executeNextJob(SchedulerQueueWorker.java:59) [atlassian-scheduler-caesium-1.3.0.jar:na]
        at com.atlassian.scheduler.caesium.impl.SchedulerQueueWorker.run(SchedulerQueueWorker.java:34) [atlassian-scheduler-caesium-1.3.0.jar:na]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_121]
        ... 16 frames trimmed```

**Comment by eddiewebb** [comment]
I think this error "invoking ActiveObjects before <ao> configuration module is enabled" means the background scheduler tried to run before a request went through BB.  (Active objects only instantiates on the first user request, and this is thrown by a scheduled jobs)


Can you re-enable the plugin once BB is running?

**Comment by eddiewebb** [comment]
https://bitbucket.org/mjensen/cqlmacro-plugin/commits/30abb5a9f8f4 might me a suitable fix (wait for properties configured to register job.

**Comment by jdesulme** [comment]
You're right the error message does appear on first startup. BB is now up and running we were just running into some performance issues where it was restarting due to OOM errors. The plugin is still enabled though...

**Comment by eddiewebb** [comment]
OK, might be OK to ignore as that job runs on increments, so first run fails, but once AO gets warmed up the next scheduled run should past.

(but yes, still need to fix this!)

**Comment by eddiewebb** [comment]
Can you find timestamp for this message?

> KEY Expiring Job Scheduled to run every [configured interval] ms. First run will trigger in ~5 seconds

Taking a look tonight, but looks like the event listener is not as truthful as hoped. Found an internal Atlassian hack to wait for all lifecycle events in set to finish before scheduling.

https://bitbucket.org/cfuller/atlassian-scheduler-jira-example/src/90a07c5af0fbd6272c034100923a50f892ce7d07/src/main/java/com/atlassian/jira/plugins/example/scheduler/impl/AwesomeLauncher.java?at=master&fileviewer=file-view-default#AwesomeLauncher.java-104


```
 * First, a disclaimer: Navigating the startup of the plugin system is unnecessarily
 * complicated.  We know this and we plan to fix it in a future version of the plugins
 * framework, but for now the solution to these problems is admittedly <em>ad hoc</em>.
```

heh

**Comment by jdesulme** [comment]
Are you looking for something like this:

```
2017-03-22 00:01:31,177 WARN  [ThreadPoolAsyncTaskExecutor::Thread 9]  c.l.f.s.s.s.KeyRotationScheduler KEY Expiring Job Scheduled to run every 86400000 ms. First run will trigger in ~5 seconds
2017-03-22 00:23:32,054 WARN  [ThreadPoolAsyncTaskExecutor::Thread 17]  c.l.f.s.s.s.KeyRotationScheduler KEY Expiring Job Scheduled to run every 86400000 ms. First run will trigger in ~5 seconds
2017-03-22 00:45:32,710 WARN  [ThreadPoolAsyncTaskExecutor::Thread 44]  c.l.f.s.s.s.KeyRotationScheduler KEY Expiring Job Scheduled to run every 86400000 ms. First run will trigger in ~5 seconds
2017-03-22 01:07:33,293 WARN  [ThreadPoolAsyncTaskExecutor::Thread 36]  c.l.f.s.s.s.KeyRotationScheduler KEY Expiring Job Scheduled to run every 86400000 ms. First run will trigger in ~5 seconds
2017-03-22 01:29:31,377 WARN  [ThreadPoolAsyncTaskExecutor::Thread 23]  c.l.f.s.s.s.KeyRotationScheduler KEY Expiring Job Scheduled to run every 86400000 ms. First run will trigger in ~5 seconds
2017-03-22 01:51:35,834 WARN  [ThreadPoolAsyncTaskExecutor::Thread 6]  c.l.f.s.s.s.KeyRotationScheduler KEY Expiring Job Scheduled to run every 86400000 ms. First run will trigger in ~5 seconds
2017-03-22 02:13:36,351 WARN  [ThreadPoolAsyncTaskExecutor::Thread 24]  c.l.f.s.s.s.KeyRotationScheduler KEY Expiring Job Scheduled to run every 86400000 ms. First run will trigger in ~5 seconds
2017-03-22 02:35:35,599 WARN  [ThreadPoolAsyncTaskExecutor::Thread 13]  c.l.f.s.s.s.KeyRotationScheduler KEY Expiring Job Scheduled to run every 86400000 ms. First run will trigger in ~5 seconds
2017-03-22 02:57:38,365 WARN  [ThreadPoolAsyncTaskExecutor::Thread 32]  c.l.f.s.s.s.KeyRotationScheduler KEY Expiring Job Scheduled to run every 86400000 ms. First run will trigger in ~5 seconds
2017-03-22 03:19:37,081 WARN  [ThreadPoolAsyncTaskExecutor::Thread 44]  c.l.f.s.s.s.KeyRotationScheduler KEY Expiring Job Scheduled to run every 86400000 ms. First run will trigger in ~5 seconds
2017-03-22 03:41:38,094 WARN  [ThreadPoolAsyncTaskExecutor::Thread 19]  c.l.f.s.s.s.KeyRotationScheduler KEY Expiring Job Scheduled to run every 86400000 ms. First run will trigger in ~5 seconds
2017-03-22 04:03:41,617 WARN  [ThreadPoolAsyncTaskExecutor::Thread 10]  c.l.f.s.s.s.KeyRotationScheduler KEY Expiring Job Scheduled to run every 86400000 ms. First run will trigger in ~5 seconds
2017-03-22 04:25:40,581 WARN  [ThreadPoolAsyncTaskExecutor::Thread 50]  c.l.f.s.s.s.KeyRotationScheduler KEY Expiring Job Scheduled to run every 86400000 ms. First run will trigger in ~5 seconds
2017-03-22 04:47:41,673 WARN  [ThreadPoolAsyncTaskExecutor::Thread 5]  c.l.f.s.s.s.KeyRotationScheduler KEY Expiring Job Scheduled to run every 86400000 ms. First run will trigger in ~5 seconds
2017-03-22 05:09:41,780 WARN  [ThreadPoolAsyncTaskExecutor::Thread 18]  c.l.f.s.s.s.KeyRotationScheduler KEY Expiring Job Scheduled to run every 86400000 ms. First run will trigger in ~5 seconds
2017-03-22 05:31:43,969 WARN  [ThreadPoolAsyncTaskExecutor::Thread 13]  c.l.f.s.s.s.KeyRotationScheduler KEY Expiring Job Scheduled to run every 86400000 ms. First run will trigger in ~5 seconds
2017-03-22 05:53:44,307 WARN  [ThreadPoolAsyncTaskExecutor::Thread 18]  c.l.f.s.s.s.KeyRotationScheduler KEY Expiring Job Scheduled to run every 86400000 ms. First run will trigger in ~5 seconds
2017-03-22 06:15:45,156 WARN  [ThreadPoolAsyncTaskExecutor::Thread 22]  c.l.f.s.s.s.KeyRotationScheduler KEY Expiring Job Scheduled to run every 86400000 ms. First run will trigger in ~5 seconds
2017-03-22 06:37:44,404 WARN  [ThreadPoolAsyncTaskExecutor::Thread 19]  c.l.f.s.s.s.KeyRotationScheduler KEY Expiring Job Scheduled to run every 86400000 ms. First run will trigger in ~5 seconds
2017-03-22 06:59:47,763 WARN  [ThreadPoolAsyncTaskExecutor::Thread 40]  c.l.f.s.s.s.KeyRotationScheduler KEY Expiring Job Scheduled to run every 86400000 ms. First run will trigger in ~5 seconds
2017-03-22 07:21:48,679 WARN  [ThreadPoolAsyncTaskExecutor::Thread 20]  c.l.f.s.s.s.KeyRotationScheduler KEY Expiring Job Scheduled to run every 86400000 ms. First run will trigger in ~5 seconds
2017-03-22 07:43:49,695 WARN  [ThreadPoolAsyncTaskExecutor::Thread 16]  c.l.f.s.s.s.KeyRotationScheduler KEY Expiring Job Scheduled to run every 86400000 ms. First run will trigger in ~5 seconds
2017-03-22 08:05:50,848 WARN  [ThreadPoolAsyncTaskExecutor::Thread 32]  c.l.f.s.s.s.KeyRotationScheduler KEY Expiring Job Scheduled to run every 86400000 ms. First run will trigger in ~5 seconds
2017-03-22 08:27:53,766 WARN  [ThreadPoolAsyncTaskExecutor::Thread 26]  c.l.f.s.s.s.KeyRotationScheduler KEY Expiring Job Scheduled to run every 86400000 ms. First run will trigger in ~5 seconds
2017-03-22 08:49:50,923 WARN  [ThreadPoolAsyncTaskExecutor::Thread 33]  c.l.f.s.s.s.KeyRotationScheduler KEY Expiring Job Scheduled to run every 86400000 ms. First run will trigger in ~5 seconds
2017-03-22 09:11:55,474 WARN  [ThreadPoolAsyncTaskExecutor::Thread 38]  c.l.f.s.s.s.KeyRotationScheduler KEY Expiring Job Scheduled to run every 86400000 ms. First run will trigger in ~5 seconds
2017-03-22 09:33:55,958 WARN  [ThreadPoolAsyncTaskExecutor::Thread 27]  c.l.f.s.s.s.KeyRotationScheduler KEY Expiring Job Scheduled to run every 86400000 ms. First run will trigger in ~5 seconds
2017-03-22 09:55:56,185 WARN  [ThreadPoolAsyncTaskExecutor::Thread 46]  c.l.f.s.s.s.KeyRotationScheduler KEY Expiring Job Scheduled to run every 86400000 ms. First run will trigger in ~5 seconds
2017-03-22 10:17:55,253 WARN  [ThreadPoolAsyncTaskExecutor::Thread 7]  c.l.f.s.s.s.KeyRotationScheduler KEY Expiring Job Scheduled to run every 86400000 ms. First run will trigger in ~5 seconds
2017-03-22 10:39:58,250 WARN  [ThreadPoolAsyncTaskExecutor::Thread 40]  c.l.f.s.s.s.KeyRotationScheduler KEY Expiring Job Scheduled to run every 86400000 ms. First run will trigger in ~5 seconds
2017-03-22 11:01:57,496 WARN  [ThreadPoolAsyncTaskExecutor::Thread 40]  c.l.f.s.s.s.KeyRotationScheduler KEY Expiring Job Scheduled to run every 86400000 ms. First run will trigger in ~5 seconds
2017-03-22 11:23:57,904 WARN  [ThreadPoolAsyncTaskExecutor::Thread 33]  c.l.f.s.s.s.KeyRotationScheduler KEY Expiring Job Scheduled to run every 86400000 ms. First run will trigger in ~5 seconds
2017-03-22 11:46:00,381 WARN  [ThreadPoolAsyncTaskExecutor::Thread 29]  c.l.f.s.s.s.KeyRotationScheduler KEY Expiring Job Scheduled to run every 86400000 ms. First run will trigger in ~5 seconds
2017-03-22 12:08:00,845 WARN  [ThreadPoolAsyncTaskExecutor::Thread 18]  c.l.f.s.s.s.KeyRotationScheduler KEY Expiring Job Scheduled to run every 86400000 ms. First run will trigger in ~5 seconds
2017-03-22 12:30:00,826 WARN  [ThreadPoolAsyncTaskExecutor::Thread 32]  c.l.f.s.s.s.KeyRotationScheduler KEY Expiring Job Scheduled to run every 86400000 ms. First run will trigger in ~5 seconds
2017-03-22 12:52:04,227 WARN  [ThreadPoolAsyncTaskExecutor::Thread 44]  c.l.f.s.s.s.KeyRotationScheduler KEY Expiring Job Scheduled to run every 86400000 ms. First run will trigger in ~5 seconds
2017-03-22 13:14:05,919 WARN  [ThreadPoolAsyncTaskExecutor::Thread 14]  c.l.f.s.s.s.KeyRotationScheduler KEY Expiring Job Scheduled to run every 86400000 ms. First run will trigger in ~5 seconds
```

**Comment by eddiewebb** [comment]
Yes, but something just before the error on 2017-03-20 15:36:29,293

It's fine now, but let me send you a new patch to try today.

**Comment by jdesulme** [comment]
Ohh unfortunately that VM is now long gone since we had a redeployment that blew recreated it.

**Comment by eddiewebb** [comment]
Jean validated in NP environments that this works and no erroring. Branch was merged to master
